#!/usr/bin/env python3
"""Generate the Rust quantity -> valid-display-units table from MoTeC's units.xml.

The .m1prj records `<Props Qty="...">` as the quantity's SI symbol (e.g. `rad/s`),
matching a `<Quantity Symbol=...>` in units.xml. A `<Locale><Default Unit="...">`
is valid for that quantity iff it equals one of the quantity's `<Unit Symbol>` /
`<Alias Symbol>` tokens (the stored form is the Symbol, not the Display glyph).
This emits a `match qty { ... }` so the check is a pure lookup. Run from the
m1-typecheck crate root (the units.xml path below is a MoTeC M1 Build install):
    python3 tools/gen_unit_table.py > src/unit_table.rs
"""
import sys
import xml.etree.ElementTree as ET

SRC = "/mnt/c/Program Files/MoTeC/Common/1.0/Units/en/units.xml"

# units.xml uses non-standard entities our note documents; ET only knows the
# XML built-ins, so the file already uses numeric refs (&#xb0;). Display strings
# decode to glyphs we don't need (Default Unit stores the Symbol form), so we
# keep Symbol + Alias tokens only, which are ASCII.

def collect(path):
    tree = ET.parse(path)
    root = tree.getroot()
    table = {}  # qty symbol -> ordered unique list of unit tokens
    for q in root.findall("Quantity"):
        qsym = q.get("Symbol")
        if not qsym:
            continue
        toks = table.setdefault(qsym, [])
        def add(t):
            # The stored `<Default Unit>` is always the ASCII Symbol form
            # (`C`, `rpm`, `kPa`, `%`, `deg`); units.xml's Alias/Display
            # fields carry inconsistently-encoded glyph variants (`°C`,
            # mojibake) that never appear as a stored unit — drop them so
            # the table is clean ASCII and can't grant false validity.
            if t and t.isascii() and t not in toks:
                toks.append(t)
        # The quantity's own SI symbol is always a valid display unit.
        add(qsym)
        for u in q.findall("Unit"):
            add(u.get("Symbol"))
            for a in u.findall("Alias"):
                add(a.get("Symbol"))
    return table

def rust_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

def main():
    table = collect(SRC)
    out = []
    out.append("//! GENERATED by tools/gen_unit_table.py from MoTeC's `units.xml` "
               "(Common/1.0/Units/en).")
    out.append("//! Do not edit by hand; re-run the generator if the units "
               "database changes.")
    out.append("//!")
    out.append("//! Maps a `<Props Qty=\"...\">` quantity symbol to the display "
               "units M1 Build accepts")
    out.append("//! for it (each `<Unit Symbol>` / `<Alias Symbol>`). A "
               "`<Default Unit>` outside this")
    out.append("//! set is M1 Build Error 1017 \"Invalid display unit\".")
    out.append("")
    out.append("/// Valid display-unit tokens for a quantity symbol, or `None` "
               "if the quantity is")
    out.append("/// not in MoTeC's units database (then the display unit can't "
               "be checked).")
    out.append("pub fn valid_display_units(qty: &str) -> Option<&'static [&'static str]> {")
    out.append("    Some(match qty {")
    for qsym in sorted(table):
        toks = table[qsym]
        joined = ", ".join(rust_str(t) for t in toks)
        out.append(f"        {rust_str(qsym)} => &[{joined}],")
    out.append("        _ => return None,")
    out.append("    })")
    out.append("}")
    out.append("")
    sys.stdout.write("\n".join(out))
    sys.stderr.write(f"quantities: {len(table)}\n")

if __name__ == "__main__":
    main()
